[tool.poetry]
name = "hs-api"
version = "0.1.0"
description = ""
authors = ["Gwenevere Frank <jfrank@ucsd.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.11"
numpy = "^2.1.2"
pyyaml = "^6.0.2"
tqdm = "^4.66.5"
connectome_utils = {git = "https://github.com/Integrated-Systems-Neuroengineering/connectome_utils.git", rev = "12ec6bf1ad6f163e166418b58661739ab5a1ee01"}
jaal = "^0.1.7"
bidict = "^0.22.0"
fxpmath = {git = "https://github.com/jfrank8/fxpmath.git", branch = "master"}
hs_bridge = {git = "ssh://git@github.com/Integrated-Systems-Neuroengineering/hs_bridge.git", rev = "fa24290d65b10ae5f429fc1c2b3b20f5f85dcf17", optional = true}
charset-normalizer = "<3.4.3"
markupsafe = "<3.0.3"
nir = "^1.0.8"

[tool.poetry.extras]
fpga = ["hs_bridge"]

[tool.poetry.group.apps.dependencies]
matplotlib = "^3.9.2"
spikingjelly = "^0.0.0.0.14"
snntorch = "^0.9.1"
tensorboard = "^2.18.0"


[tool.poetry.group.dev.dependencies]
pylint = "^3.3.4"
black = "^25.1.0"
pytest = "^9.0.2"

[tool.poetry.group.docs.dependencies]
sphinx = "^8.0"
sphinx-design = "^0.6"
sphinx-gallery = "^0.18"
sphinxcontrib-bibtex = "^2.6"
pydata-sphinx-theme = "^0.16"
myst-parser = "^4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.format]
max-line-length = "88"
