[tool.poetry]
name = "hs-api"
version = "0.1.0"
description = ""
authors = ["Gwenevere Frank <jfrank@ucsd.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "^2.1.2"
pyyaml = "^6.0.2"
tqdm = "^4.66.5"
connectome_utils = {git = "https://github.com/Integrated-Systems-Neuroengineering/connectome_utils.git", branch = "dev"}
bidict = "^0.22.0"
fxpmath = {git = "https://github.com/jfrank8/fxpmath.git", branch = "master"}

[tool.poetry.group.apps.dependencies]
jaal = "^0.1.7"
matplotlib = "^3.9.2"
spikingjelly = "^0.0.0.0.14"
snntorch = "^0.9.1"
tensorboard = "^2.18.0"

[tool.poetry.group.fpga]
optional = true

[tool.poetry.group.fpga.dependencies]
hs_bridge = {git = "git@github.com:Integrated-Systems-Neuroengineering/hs_bridge.git", branch = "dev", python = ">3.11,<3.12"}


[tool.poetry.group.docs.dependencies]
sphinx = "^8.0"
myst-parser = "^4.0"
sphinx-design = "^0.6"
sphinx-gallery = "^0.18"
sphinxcontrib-bibtex = "^2.6"
pydata-sphinx-theme = "^0.16"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.4"
black = "^25.1.0"
scalene = "^2.0.1"
pytest = "^9.0.2"
pre-commit = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.format]
max-line-length = "88"
